### ISSUE TITLE
Project does not compile

### ISSUE THREAD

**Issue by stevenh2** [doowb/handlebars-helpers-browserify-example#4]
Also missing compilation instructions

**Comment by doowb** [comment]
I'm going to update this to make it easier to focus on the browserify and handlebars-helpers parts instead of having to know what's being done in the gulpfile.

For now, the following should be done:

- Install gulp-cli:
  ```bash
  $ npm install gulp-cli --global
  ```
- Clone this package:
  ```bash
  $ git clone https://github.com/doowb/handlebars-helpers-browserify-example.git
  $ cd handlebars-helpers-browserify-example.git
  ```
- Install npm dependencies:
  ```bash
  $ npm install
  ```
- Run gulp to build and open the project in the browser:
  ```bash
  $ gulp dev
  ```

If this doesn't work, please reopen this issue and add additional information so I can understand what's wrong.
